Fix for unwanted deletion of non-synced new TEI when its 2nd enrollment is cancelled
EyeSeeTea/dhis2-android-capture-app pull request #179
Opened 2024-09-25 10:21 UTC by alex-vt

## Description

An issue of the logic of cleanup when a newly created, not synced yet TEI is being enrolled into another program, and the user backs out of the 2nd enrollment screen by discarding the changes in the pop-up bottom sheet dialog. The issue occurred in `app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt` in `deleteAllSavedData`.

## Solution description

A check is added in `deleteAllSavedData` to delete the entire non-synced TEI only when there are no enrollments in other programs than the one being cancelled.

## Covered unit test cases

Unit tests for the new behavior of `deleteAllSavedData` added to `app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt`.

2024-09-26 14:07 UTC, xurxodev requested changes
thanks @alex-vt 

It seems a good fix, however I've found some issues about clean code to improve.

I've added comments in the code

2024-09-26 14:07 UTC, xurxodev commented on app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
> +    private fun isTeiInNoOtherProgram(): Boolean =
This application follow some bad practices, and we would like to follow best practices when we add customizations or fixes.

From a presenter we avoid use directly d2. 

We try to use d2 in an uncoupled way using repositories, the advantage is if they change d2 in the future, the change in encapsulated in the repositories instead of to change a lot of places in presenters or somewhere.

In this case, is a better option to move isTeiInNoOtherProgram function to some repository (enrollmentRepository seems the best option here)

2024-09-26 14:07 UTC, xurxodev commented on app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
> +
In the test we like to user three blocks (preparation, execution and verification).

Please Try reduce the code inside of every test breaking down in functions.
For example:
givenATei (status)
givenAprogram()

In these functions you create TEI, program and stub functions in repositories returning the TEI or program.

Using this functions you can avoid the duplicate code that exist currently in these tests.

2024-09-30 14:46 UTC, alex-vt commented on app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
> +    private fun isTeiInNoOtherProgram(): Boolean =
Thank you for the suggestion. `EnrollmentRepository` and other repositories in `EnrollmentPresenterImpl` do not have the direct `D2` dependency. Passing `isTeiInNoOtherProgram` deeper would probably be unproportional to how limited its usage is. I see that such narrow context functions are extracted into utils, such as https://github.com/EyeSeeTea/dhis2-android-capture-app/blob/develop-simprints/app/src/main/java/org/dhis2/data/biometrics/utils/GetTeiByUid.kt that's also used in `EnrollmentPresenterImpl`. I've extracted `isTeiInNoOtherProgram` in a similar way.

2024-10-02 08:23 UTC, xurxodev commented on app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
> +    private fun isTeiInNoOtherProgram(): Boolean =
@alex-vt EnrollmentRepository doesn't have direct D2 dependency, but it has EnrollmentConfiguration dependency and this one has D2 dependency.

It's possible to move your  isTeiInNoOtherProgram function to EnrollmentConfiguration to use from EnrollmentRepository.

So we avoid use d2 from presenter to add this fix even passing as parameter to a new function used from presenter.

2024-10-02 08:24 UTC, xurxodev requested changes
thanks @alex-vt 

I've leaved a reply to your comment

2024-10-07 05:48 UTC, xurxodev approved these changes
thanks @alex-vt

2024-10-21 07:25 UTC, merged