Sequential search result list viewing from beginning
EyeSeeTea/dhis2-android-capture-app pull request #221
Opened 2024-12-03 13:45 UTC by alex-vt

Behavior before:

* In Programs with sequential search (with biometrics enabled), search results could appear pre-scrolled down from the beginning of the list, depending on list contents and scroll position before search.

Behavior after:

* Search results are shown from the beginning for every stage of sequential search.

2024-12-04 11:57 UTC, xurxodev requested changes
thanks @alex-vt 

It's not necessary to save a previous sequential Search in a new mutable variable and unsafe.

I think is better solution if you call to scrollToPosition when search helper screen is called when setSearchScreen method in SearchTEIViewModel is called and biometrics mode is not full

2024-12-04 18:41 UTC, alex-vt commented
Thank you @xurxodev, monitoring the LiveData for the scroll-up decision is a cleaner way indeed. For the condition when to scroll up, just the changes of `SequentialSearch` should still be a good fit - the issue occurred when advancing to a new stage of sequential search.

2024-12-05 07:20 UTC, xurxodev approved these changes
thanks @alex-vt

2024-12-09 11:43 UTC, ifoche approved these changes
thanks @alex-vt @xurxodev

2024-12-09 11:43 UTC, merged